print("Por favor, ingrese los siguientes datos")
print("Nombre Completo:")
a = input()
b = input("Fecha de Nacimiento:")
c = "Clinica Gutierrez. Alvear 122"
print("ingrese los datos del medicamento:")
print("Nombre del medicamento:")
d = input()
print("Dosis en Miligramos:")
e = input()
print("Horas entre cada toma del medicamento")
f = input()
print("***RECETA MEDICA***")
print("Nombre del paciente: ", a)
print("Fecha de Nacimiento: ", b)
print("Nombre del Medicamento: ", d)
print("Dosis:", e, "mm")
print("Tomar 1 dosis cada ", f, "horas")
print(c)